name: Ubuntu VNC

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop Environment & VNC
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies tightvncserver git python3 -y
          mkdir -p ~/.vnc
          echo "chatgpt" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1 -geometry 1280x720 -depth 24

      - name: Setup noVNC Server
        run: |
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify
          cd ~/noVNC
          nohup python3 ./utils/novnc_proxy --vnc localhost:5901 --listen 6080 &
          sleep 10
